### ISSUE TITLE
Eurostar publishes a GTFS

### ISSUE THREAD

**Issue by AntoineAugusti** [planarnetwork/eurostar2gtfs#10]
Just to let you know that our team @ transport.data.gouv.fr worked with Eurostar to make sure that they publish a GTFS file.

See https://transport.data.gouv.fr/datasets/eurostar-gtfs

**Comment by linusnorton** [comment]
Thank you and well done. I will update the README to reflect that.

**Comment by AntoineAugusti** [comment]
Perfect, thanks!
